### ISSUE TITLE
Error 500 on eloise.pajbot.com

### ISSUE THREAD

**Issue by TranRed** [pajbot/pajbot.com#3]
Trying to access certain user pages on eloise.pajbot.com leads to an internal server error.
Examples: 
- [transcendence9](https://eloise.pajbot.com/user/transcendence9)
- [eloise_ailv](https://eloise.pajbot.com/user/eloise_ailv)
- [huurrrduurrr](https://eloise.pajbot.com/user/huurrrduurrr)

Other pages work fine:
- [pajlada](https://eloise.pajbot.com/user/pajlada)
- [tranred](https://eloise.pajbot.com/user/tranred)

<img width="381" alt="professional screenshot" src="https://cloud.githubusercontent.com/assets/16636423/14064787/6c6d36cc-f410-11e5-8021-8f48bb6cff28.png">

**Comment by pajlada** [comment]
Fixed, thanks
